name: Appium Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java 17 and make it the default Java version
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Verify Java version
      - name: Verify Java version
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install and configure Appium
        run: |
          npm install -g appium@next
          appium driver install uiautomator2

      - name: Start Appium Server
        run: |
          appium --log appium.log &
          echo "Waiting for Appium to start..."
          sleep 5

      # Use the pre-built emulator in GitHub Actions
      - name: Run tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: pixel
          script: |
            echo "Emulator is running"
            adb devices
            
            # List files to ensure APK is found
            find . -name "*.apk" || echo "No APK files found"
            
            # Install APK
            find . -name "*.apk" -exec adb install {} \; || echo "Failed to install APK"
            
            # Set up configuration
            mkdir -p src/test/resources/config
            cp src/test/resources/config/github-actions-config.properties src/test/resources/config/config.properties || echo "Failed to copy config file"
            
            # Show Java version inside emulator script
            java -version
            
            # Run Maven tests - specify max heap size to avoid memory issues
            export MAVEN_OPTS="-Xmx2048m"
            mvn clean test

      - name: Debug on failure
        if: failure()
        run: |
          echo "Debug information on failure:"
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          ls -la
          echo "Appium log:"
          cat appium.log || echo "No appium.log file found"
          echo "Maven logs:"
          find ~/.m2 -name "*.log" -exec cat {} \; || echo "No Maven logs found"