name: Appium Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium --log appium.log &

      - name: Create and start emulator
        run: |
          echo "no" | avdmanager create avd --force --name test --package "system-images;android-30;google_apis;x86_64"
          emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          adb devices

      - name: Install APK
        run: |
          adb install ./resources/apps/TUIChallengeApp.apk
          sleep 5

      - name: Copy GitHub Actions config
        run: |
          mkdir -p src/test/resources/config
          cp src/test/resources/config/github-actions-config.properties src/test/resources/config/config.properties

      - name: Run tests
        run: mvn clean test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            target/cucumber-reports/
            appium.log