name: Basic Sauce Labs Demo

# Run manually or on schedule rather than on every push to avoid consuming minutes
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      # Run only one test to stay within free tier limits
      - name: Run single test on Sauce Labs
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          # Create config directory if it doesn't exist
          mkdir -p src/test/resources/config
          
          # Create the sauce-config.properties file with credentials
          cat > src/test/resources/config/sauce-config.properties << EOF
          # Sauce Labs Configuration
          appium.server.url=https://ondemand.eu-central-1.saucelabs.com/wd/hub
          sauce.username=${SAUCE_USERNAME}
          sauce.accesskey=${SAUCE_ACCESS_KEY}
          
          # Platform Settings
          platform.name=Android
          device.name=Android GoogleAPI Emulator
          platform.version=11.0
          automation.name=UiAutomator2
          
          # App Settings
          app.sauce.id=sauce-storage:YourApp.apk
          
          # Test Configuration
          test.name=Demo Test Run
          test.build=Build-${GITHUB_RUN_NUMBER}
          
          # Timeouts and Stability
          implicit.wait.ms=5000
          newCommandTimeout=180
          autoGrantPermissions=true
          EOF
          
          # Copy to config.properties for the test run
          cp src/test/resources/config/sauce-config.properties src/test/resources/config/config.properties
          
          # Run a single test class to stay within free tier limits
          # Replace LoginTest with your actual test class name
          mvn test -Dtest=LoginRunnerTest

      - name: Debug info on failure
        if: failure()
        run: |
          echo "Debug information:"
          echo "-----------------"
          echo "Sauce Labs dashboard: https://app.saucelabs.com/dashboard/tests/vdc"
          echo "Check your email associated with Sauce Labs for error notifications"