name: Sauce Labs Appium Tests

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Setup configuration for Sauce Labs
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          # Create directory if it doesn't exist
          mkdir -p src/test/resources/config
          
          # Copy Sauce Labs configuration template if it exists, otherwise create it
          if [ -f src/test/resources/config/sauce-config.properties ]; then
            cp src/test/resources/config/sauce-config.properties src/test/resources/config/config.properties
          else
            # Create the config file directly if template doesn't exist
            cat > src/test/resources/config/config.properties << EOF
          # Sauce Labs Configuration
          appium.server.url=https://ondemand.us-west-1.saucelabs.com/wd/hub
          sauce.username=$SAUCE_USERNAME
          sauce.accesskey=$SAUCE_ACCESS_KEY
          
          # Platform Settings
          platform.name=Android
          device.name=Google Pixel 6
          platform.version=12.0
          automation.name=UiAutomator2
          no.reset=true
          autoGrantPermissions=true
          
          # App Settings
          app.package=com.tui.qa.challenge
          app.activity=com.tui.qa.challenge.MainActivity
          
          # Test Configuration
          test.name=TUI Challenge App Test
          test.build=Appium-Tests-CI-$GITHUB_RUN_NUMBER
          
          # Timeouts and Waits
          implicit.wait.ms=1000
          EOF
          fi
          
          # Replace placeholders with actual secrets
          sed -i "s/YOUR_SAUCE_USERNAME/$SAUCE_USERNAME/g" src/test/resources/config/config.properties
          sed -i "s/YOUR_SAUCE_ACCESS_KEY/$SAUCE_ACCESS_KEY/g" src/test/resources/config/config.properties
          
          # Upload app to Sauce Labs storage if needed
          # This step is optional if you've already uploaded your app or set the app.sauce.id in your config
          # SAUCE_APP_ID=$(curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" -X POST -H "Content-Type: application/octet-stream" \
          #                   "https://saucelabs.com/rest/v1/storage/$SAUCE_USERNAME/your-app.apk?overwrite=true" \
          #                   --data-binary @"./path/to/your/app.apk")
          # 
          # if [ ! -z "$SAUCE_APP_ID" ]; then
          #   echo "app.sauce.id=sauce-storage:your-app.apk" >> src/test/resources/config/config.properties
          # fi

      - name: Run tests on Sauce Labs
        run: |
          # Run your tests
          mvn clean test